# Generated by Django 4.2.7 on 2023-12-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0004_remove_layout_brothers_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art_work',
            new_name='ArtWork',
        ),
        migrations.DeleteModel(
            name='Brother',
        ),
    ]
