# Generated by Django 4.2.7 on 2023-12-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0005_rename_art_work_artwork_delete_brother'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_gardens', models.ImageField(upload_to='dynamic_images', verbose_name='The Gardens Image')),
                ('the_brothers', models.ImageField(upload_to='dynamic_images', verbose_name='The Brothers Image')),
                ('retreat_center', models.ImageField(upload_to='dynamic_images', verbose_name='Retreat Center Image')),
            ],
        ),
    ]
