# Generated by Django 4.2.7 on 2023-12-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='retreat_center',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Retreat Center Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='the_brothers',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='The Brothers Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='the_gardens',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='The Gardens Image'),
        ),
    ]
