# Generated by Django 4.2.7 on 2023-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0007_alter_image_retreat_center_alter_image_the_brothers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='about_the_center',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='About the Center Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='meditation_garden',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Meditation Garden of Truth & Reconciliation Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='our_daily_life',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Our Daily Life Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='pray_with_us',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Pray With Us Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='the_gardens_and_scenery',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='The Gardens & Scenery Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='vacation',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Vacation Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='virtual_tour',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Virtual Tour Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='watch_video',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Watch Video Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='who_we_are',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Who We Are Image'),
        ),
    ]
