# Generated by Django 4.2.7 on 2023-12-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0009_image_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_lady_of_mepkin', models.TextField(verbose_name='Our Lady of Mepkin Text')),
                ('lauren_cemetry', models.TextField(verbose_name="Lauren's Cemetry Text")),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='img',
            field=models.ImageField(default='', upload_to='artworks'),
        ),
    ]
