# Generated by Django 4.2.8 on 2023-12-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0011_alter_text_lauren_cemetry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layout',
        ),
    ]
