# Generated by Django 4.2.8 on 2024-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0012_delete_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='francis_artwork',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_images', verbose_name='Francis Artwork Image'),
        ),
    ]
