# Generated by Django 4.2.8 on 2024-01-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0014_remove_image_vacation_image_vocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtWork',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
