# Generated by Django 4.2.8 on 2024-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
