# Generated by Django 4.2.8 on 2024-01-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0017_prayerrequest_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrayerRequest',
            new_name='Pray',
        ),
        migrations.RenameField(
            model_name='pray',
            old_name='prayer_request',
            new_name='prayer_msg',
        ),
    ]
