# Generated by Django 4.2.8 on 2024-01-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0018_rename_prayerrequest_pray_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pray',
            new_name='Prayer',
        ),
    ]
