# Generated by Django 4.2.8 on 2024-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0019_rename_pray_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MepkinDailyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
