# Generated by Django 4.2.8 on 2024-01-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0020_mepkindailyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mepkindailyword',
            options={'ordering': ['-created']},
        ),
    ]
