# Generated by Django 4.2.8 on 2024-02-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0021_alter_mepkindailyword_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
