# Generated by Django 4.2.8 on 2024-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0022_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='content',
            field=models.CharField(default='Add Bio', max_length=200),
        ),
    ]
