# Generated by Django 4.2.8 on 2024-02-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0023_alter_bio_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mepkindailyword',
            options={},
        ),
        migrations.AlterField(
            model_name='bio',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
