# Generated by Django 4.2.8 on 2024-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0024_alter_mepkindailyword_options_alter_bio_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mepkindailyword',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='bio',
            name='content',
            field=models.CharField(default='Add Bio', max_length=200),
        ),
    ]
