# Generated by Django 4.2.8 on 2024-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0025_alter_mepkindailyword_options_alter_bio_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mepkindailyword',
            name='post',
            field=models.TextField(max_length=200),
        ),
    ]
