# Generated by Django 4.2.8 on 2024-02-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0026_alter_mepkindailyword_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_msg',
            field=models.CharField(max_length=2000),
        ),
    ]
