# Generated by Django 4.2.8 on 2024-03-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0027_alter_prayer_prayer_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
