# Generated by Django 4.2.8 on 2024-03-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0030_visitor_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user_agent',
        ),
    ]
