# Generated by Django 4.2.8 on 2024-03-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0031_remove_visitor_session_key_remove_visitor_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='current_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
