# Generated by Django 4.2.8 on 2024-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0033_visitor_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='retreat_offerings/')),
            ],
        ),
    ]
