# Generated by Django 4.2.8 on 2024-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0034_retreatoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatoffering',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='retreatofferings/'),
        ),
    ]
