# Generated by Django 4.2.8 on 2024-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0035_alter_retreatoffering_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreatoffering',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retreatoffering',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retreatoffering',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
