# Generated by Django 4.2.8 on 2025-03-03 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Src_App", "0037_retreatoffering_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("duration", models.IntegerField(default=0)),
                (
                    "most_clicked_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
