# Generated by Django 4.2.8 on 2025-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Src_App", "0038_visitoractivity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitoractivity",
            old_name="start_time",
            new_name="first_visit",
        ),
        migrations.RenameField(
            model_name="visitoractivity",
            old_name="duration",
            new_name="total_time_spent",
        ),
        migrations.RemoveField(
            model_name="visitoractivity",
            name="most_clicked_url",
        ),
        migrations.AddField(
            model_name="visitoractivity",
            name="page_visits",
            field=models.JSONField(default=dict),
        ),
    ]
