# Generated by Django 4.2.8 on 2025-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Src_App", "0039_rename_start_time_visitoractivity_first_visit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitoractivity",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
