# Generated by Django 4.2.8 on 2025-03-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0041_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('psalter', 'Psalter Artwork'), ('francis', 'Francis Artwork')], default='psalter', max_length=20),
        ),
    ]
